// Car catalog + lootbox/prize metadata. Pure data module (no economy require)
// so it can be required by economy.js without a circular dependency.
//
// Car stats live in cars.json (generated by gen-cars.js) and are PERMANENT.

const data = require("./cars.json");

const TYPE_ORDER = ["shitbox", "beater", "street", "sports", "super", "hyper", "hovercar"];
const RARITY_ORDER = ["common", "uncommon", "rare", "legendary", "mythical"];

// Per-type metadata: lootbox price + race prizes [1st,2nd,3rd] (already toned down).
const TYPES = {
  shitbox: { key: "shitbox", label: "Shitbox", lootbox: 2500, prizes: [10000, 5000, 2500] },
  beater: { key: "beater", label: "Beater", lootbox: 25000, prizes: [100000, 50000, 25000] },
  street: { key: "street", label: "Street Car", lootbox: 250000, prizes: [1000000, 500000, 250000] },
  sports: { key: "sports", label: "Sports Car", lootbox: 2500000, prizes: [10000000, 5000000, 2500000] },
  super: { key: "super", label: "Super Car", lootbox: 25000000, prizes: [100000000, 50000000, 25000000] },
  hyper: { key: "hyper", label: "Hyper Car", lootbox: 250000000, prizes: [1000000000, 500000000, 250000000] },
  hovercar: { key: "hovercar", label: "Hovercar", lootbox: 25000000000000, prizes: [100000000000000, 50000000000000, 25000000000000] },
};

// Per-rarity metadata: unbox % (tier roll), embed color, emoji dot.
const RARITY = {
  common: { key: "common", label: "Common", unbox: 35, color: 0x95a5a6, emoji: "\u26AA" },
  uncommon: { key: "uncommon", label: "Uncommon", unbox: 30, color: 0x2ecc71, emoji: "\uD83D\uDFE2" },
  rare: { key: "rare", label: "Rare", unbox: 25, color: 0x3498db, emoji: "\uD83D\uDD35" },
  legendary: { key: "legendary", label: "Legendary", unbox: 7, color: 0xf1c40f, emoji: "\uD83D\uDFE1" },
  mythical: { key: "mythical", label: "Mythical", unbox: 3, color: 0xe91e63, emoji: "\uD83D\uDD34" },
};

// ── Indexes ────────────────────────────────────────────────────
const BY_ID = {};
for (const c of data) BY_ID[c.id] = c;

const BY_TYPE = {};
for (const t of TYPE_ORDER) {
  BY_TYPE[t] = {};
  for (const r of RARITY_ORDER) BY_TYPE[t][r] = [];
}
for (const c of data) {
  if (BY_TYPE[c.type] && BY_TYPE[c.type][c.rarity]) BY_TYPE[c.type][c.rarity].push(c);
}

function carById(id) { return BY_ID[id] || null; }
function listType(type) { return data.filter((c) => c.type === type); }
function listTypeRarity(type, rarity) { return (BY_TYPE[type] && BY_TYPE[type][rarity]) || []; }
function allCars() { return data.slice(); }

// Normalize a user-typed car-type/race-type into a canonical key.
function normalizeType(input) {
  if (!input) return null;
  let s = String(input).toLowerCase().replace(/[^a-z]/g, "");
  if (s.endsWith("car") && s !== "car") s = s.slice(0, -3); // "streetcar" -> "street"
  const map = {
    shitbox: "shitbox", shit: "shitbox", sb: "shitbox",
    beater: "beater", beat: "beater",
    street: "street",
    sports: "sports", sport: "sports",
    super: "super",
    hyper: "hyper",
  };
  return map[s] || (TYPE_ORDER.includes(s) ? s : null);
}

// Weighted random rarity using the tier unbox percentages.
function rollRarity(rng) {
  const r = (rng || Math.random)();
  const total = RARITY_ORDER.reduce((a, k) => a + RARITY[k].unbox, 0);
  let acc = 0;
  const target = r * total;
  for (const k of RARITY_ORDER) {
    acc += RARITY[k].unbox;
    if (target < acc) return k;
  }
  return RARITY_ORDER[0];
}

// Open one lootbox of a given type: roll rarity, then pick a car within that
// (type,rarity) bucket weighted by each car's `weight` (better cars are rarer).
function openBox(type, rng) {
  const rand = rng || Math.random;
  let rarity = rollRarity(rand);
  let bucket = listTypeRarity(type, rarity);
  // Fallback if a bucket is somehow empty: walk down to a populated rarity.
  if (!bucket.length) {
    for (let i = RARITY_ORDER.indexOf(rarity); i >= 0; i--) {
      bucket = listTypeRarity(type, RARITY_ORDER[i]);
      if (bucket.length) { rarity = RARITY_ORDER[i]; break; }
    }
  }
  if (!bucket.length) return null;
  const totalW = bucket.reduce((a, c) => a + (c.weight || 1), 0);
  let target = rand() * totalW;
  for (const c of bucket) {
    target -= c.weight || 1;
    if (target <= 0) return c;
  }
  return bucket[bucket.length - 1];
}

module.exports = {
  TYPE_ORDER,
  RARITY_ORDER,
  TYPES,
  RARITY,
  carById,
  listType,
  listTypeRarity,
  allCars,
  normalizeType,
  rollRarity,
  openBox,
};
