// Pet breed catalog + per-instance rollers. Pure data/util module (no economy
// require) so pets.js can require it freely.
//
// breeds.json is generated by gen-pets.js and is PERMANENT. Per-pet stats,
// size, weight and value are rolled here when a pet is created/born.

const data = require("./breeds.json");

const RARITY_ORDER = ["common", "uncommon", "rare", "legendary", "mythical"];
const SIZE_ORDER = ["toy", "small", "medium", "large", "giant"];
const SPECIES = ["dog", "cat"];

const MAX_NATURAL_SIZE = 18; // natural breeding cap
const MAX_POTION_SIZE = 30;  // self-breed potion cap (exponential past 18)

const RARITY = {
  common: { key: "common", label: "Common", unbox: 35, color: 0x95a5a6, emoji: "\u26AA", band: [25, 45], base: 5e3 },
  uncommon: { key: "uncommon", label: "Uncommon", unbox: 30, color: 0x2ecc71, emoji: "\uD83D\uDFE2", band: [40, 58], base: 5e4 },
  rare: { key: "rare", label: "Rare", unbox: 25, color: 0x3498db, emoji: "\uD83D\uDD35", band: [55, 72], base: 1e6 },
  legendary: { key: "legendary", label: "Legendary", unbox: 7, color: 0xf1c40f, emoji: "\uD83D\uDFE1", band: [70, 86], base: 5e8 },
  mythical: { key: "mythical", label: "Mythical", unbox: 3, color: 0xe91e63, emoji: "\uD83D\uDD34", band: [85, 99], base: 5e9 },
};

const SPECIES_EMOJI = { dog: "\uD83D\uDC36", cat: "\uD83D\uDC31", hybrid: "\uD83E\uDDEC" };

// ── Indexes ──────────────────────────────────────────
const BY_KEY = {};
const BY_SPECIES_RARITY = { dog: {}, cat: {} };
for (const s of SPECIES) for (const r of RARITY_ORDER) BY_SPECIES_RARITY[s][r] = [];
for (const b of data) {
  BY_KEY[b.key] = b;
  if (BY_SPECIES_RARITY[b.species] && BY_SPECIES_RARITY[b.species][b.rarity]) {
    BY_SPECIES_RARITY[b.species][b.rarity].push(b);
  }
}

function getBreed(key) { return BY_KEY[key] || null; }
function allBreeds() { return data.slice(); }
function listSpecies(species) { return data.filter((b) => b.species === species); }

function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

// Weighted rarity roll using unbox percentages (same curve as car lootboxes).
function rollRarity(rng) {
  const r = (rng || Math.random)();
  const total = RARITY_ORDER.reduce((a, k) => a + RARITY[k].unbox, 0);
  let acc = 0, target = r * total;
  for (const k of RARITY_ORDER) {
    acc += RARITY[k].unbox;
    if (target < acc) return k;
  }
  return RARITY_ORDER[0];
}

// Pick a random breed of a species, optionally forcing a rarity.
function rollBreed(species, rng, forcedRarity) {
  const rand = rng || Math.random;
  let rarity = forcedRarity || rollRarity(rand);
  let bucket = BY_SPECIES_RARITY[species][rarity];
  if (!bucket || !bucket.length) {
    for (let i = RARITY_ORDER.indexOf(rarity); i >= 0; i--) {
      bucket = BY_SPECIES_RARITY[species][RARITY_ORDER[i]];
      if (bucket && bucket.length) { rarity = RARITY_ORDER[i]; break; }
    }
  }
  if (!bucket || !bucket.length) return null;
  return bucket[Math.floor(rand() * bucket.length)];
}

// Roll the three 0-100 stats around the rarity band, nudged by size.
function rollStats(rarity, size, rng) {
  const rand = rng || Math.random;
  const band = (RARITY[rarity] || RARITY.common).band;
  const sizeNudge = ((size || 0) / MAX_NATURAL_SIZE) * 8 - 2; // bigger = a touch stronger
  const one = () => Math.round(clamp(band[0] + rand() * (band[1] - band[0]) + sizeNudge, 1, 100));
  const speed = one(), stamina = one(), temperament = one();
  const overall = Math.round((speed + stamina + temperament) / 3);
  return { speed, stamina, temperament, overall };
}

// Natural size roll (0-18), gently centered.
function rollSize(rng) {
  const rand = rng || Math.random;
  return Math.round(((rand() + rand()) / 2) * MAX_NATURAL_SIZE * 10) / 10;
}

// Self-breed POTION size roll (0-30). Each point past 18 is exponentially
// harder, so high rolls are rare and precious.
function rollPotionSize(rng) {
  const rand = rng || Math.random;
  const base = rand() * MAX_NATURAL_SIZE; // 0-18 easy part
  // bonus 0-12 but heavily back-loaded: pow(8) means most rolls add little.
  const bonus = Math.pow(rand(), 8) * (MAX_POTION_SIZE - MAX_NATURAL_SIZE);
  return Math.round((base + bonus) * 10) / 10;
}

// Derive a weight (lbs) inside the breed's size band, scaled by size 0-18(+).
function weightForSize(breed, size) {
  if (!breed) return Math.round(10 + (size || 0));
  const frac = clamp((size || 0) / MAX_NATURAL_SIZE, 0, 2); // potion can exceed 1
  const w = breed.weightMin + (breed.weightMax - breed.weightMin) * Math.min(1, frac);
  // size beyond natural keeps adding weight past the breed max (freak specimens)
  const over = Math.max(0, (size || 0) - MAX_NATURAL_SIZE);
  return Math.round(w + over * (breed.weightMax - breed.weightMin) * 0.08);
}

// Sell/market value of an ordinary pet (NOT lab hybrids — see hybridValue).
function valueOf(pet) {
  const r = RARITY[pet.rarity] || RARITY.common;
  const size = pet.size || 0;
  let sizeFactor;
  if (size <= MAX_NATURAL_SIZE) sizeFactor = 1 + size / 9;          // up to 3x
  else sizeFactor = 3 * Math.pow(1.7, size - MAX_NATURAL_SIZE);      // potron freaks explode
  const purebredMult = pet.purebred ? 2 : 1;
  const statFactor = 0.5 + ((pet.stats && pet.stats.overall) || 50) / 100; // 0.5-1.5
  const weightFactor = 1 + (pet.weight || 0) / 300;
  const v = r.base * sizeFactor * purebredMult * statFactor * weightFactor;
  return Math.max(1, Math.floor(v));
}

// Lab dog-cat hybrid value: 5 quadrillion .. 500 quadrillion, with the very
// top end (~1%) being a rare jackpot. Better parents raise the floor.
const HYBRID_MIN = 5e15;   // 5 quadrillion
const HYBRID_MAX = 5e17;   // 500 quadrillion
function hybridValue(rng, dogOverall, catOverall) {
  const rand = rng || Math.random;
  const quality = clamp(((dogOverall || 50) + (catOverall || 50)) / 200, 0, 1); // 0-1
  const luck = Math.pow(rand(), 4); // back-loaded: high luck is rare (~2.6% > 0.9)
  const statMult = 0.6 + 0.4 * quality; // 0.6-1.0
  const v = HYBRID_MIN + (HYBRID_MAX - HYBRID_MIN) * luck * statMult;
  return Math.max(HYBRID_MIN, Math.floor(v));
}

// ── Pound rescue payout ──────────────────────────────
// The pound is meant to be a humble, grind-friendly source — NOT a jackpot
// machine. Most rescues land 50k-200k; a decent pull reaches ~500k; only a rare
// lucky pull approaches 1M. The value is FIXED at adoption (stored on the pet)
// so it can't balloon through the size/purebred/stat multipliers in valueOf.
const POUND_FLOOR = 5e4;     // 50k (matches adopt cost — worst case ~break even)
const POUND_TYPICAL = 2e5;   // 200k — top of the everyday band
const POUND_GOOD = 5e5;      // 500k — a genuinely good pull
const POUND_JACKPOT = 1e6;   // ~1M dream pull (really lucky)
function poundValue(rng) {
  const rand = rng || Math.random;
  const roll = rand();
  let v;
  if (roll < 0.80) {
    // 80%: the bread-and-butter 50k-200k
    v = POUND_FLOOR + rand() * (POUND_TYPICAL - POUND_FLOOR);
  } else if (roll < 0.97) {
    // 17%: a nice 200k-500k pull
    v = POUND_TYPICAL + rand() * (POUND_GOOD - POUND_TYPICAL);
  } else {
    // 3%: jackpot 500k-1M, back-loaded so true ~1M pulls are rare
    v = POUND_GOOD + Math.pow(rand(), 2) * (POUND_JACKPOT - POUND_GOOD);
  }
  return Math.max(1, Math.floor(v));
}
// Map a pound payout to a rarity tier (drives the card emoji + stat band only).
function rarityForValue(v) {
  if (v >= 7e5) return "legendary";
  if (v >= 3e5) return "rare";
  if (v >= 1.2e5) return "uncommon";
  return "common";
}

module.exports = {
  RARITY_ORDER,
  SIZE_ORDER,
  SPECIES,
  RARITY,
  SPECIES_EMOJI,
  MAX_NATURAL_SIZE,
  MAX_POTION_SIZE,
  HYBRID_MIN,
  HYBRID_MAX,
  getBreed,
  allBreeds,
  listSpecies,
  rollRarity,
  rollBreed,
  rollStats,
  rollSize,
  rollPotionSize,
  weightForSize,
  valueOf,
  hybridValue,
  poundValue,
  rarityForValue,
};
